/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Beans/Customizer.java to edit this template
 */
package com.mycompany.poojavaext.frames;

import com.mycompany.poojavaext.Produto;
import com.mycompany.poojavaext.PooJavaExt;
import java.sql.Connection;
import java.util.ArrayList;

/**
 *
 * @author Deus Est Geba Giorno
 */
public class ProdutoForm extends javax.swing.JPanel implements java.beans.Customizer {
    
    private Integer codigo;
    private Float valorvenda;
    private Integer quantEstoque;
    private String strCodigo;
    private String strValor;
    private String strQuantidade;
    private final Connection conexaoMySQL;
    private final PooJavaExt mainFrame;
    private final ArrayList<Produto> produto;
    private Object bean;

    public ProdutoForm(Connection conexaoMySQL, PooJavaExt mainFrame, ArrayList<Produto> produtos) {
        initComponents();
        
        this.conexaoMySQL = conexaoMySQL;
        this.mainFrame = mainFrame;
        this.produto = produtos;
    
    }
    private Produto encontrarProduto(int codigo) {
        Produto produtoEncontrado = null;
        for (Produto c : produto) {
            if (c.getCodigo() == codigo) {
                produtoEncontrado = c;
                break;
            } else {
            }
    };
        
        return produtoEncontrado;
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Buscar Produto");
        jLayeredPane1.add(jLabel1);
        jLabel1.setBounds(10, 10, 90, 16);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jTextField1);
        jTextField1.setBounds(10, 30, 280, 22);

        jButton1.setText("Buscar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton1);
        jButton1.setBounds(310, 30, 72, 23);

        jLabel3.setText("Código");
        jLayeredPane1.add(jLabel3);
        jLabel3.setBounds(100, 60, 40, 16);

        jTextField2.setName("EntradaCodigo"); // NOI18N
        jLayeredPane1.add(jTextField2);
        jTextField2.setBounds(160, 60, 190, 22);

        jLabel4.setText("Descrição");
        jLayeredPane1.add(jLabel4);
        jLabel4.setBounds(90, 90, 51, 16);
        jLayeredPane1.add(jTextField3);
        jTextField3.setBounds(160, 90, 190, 22);

        jLabel5.setText("Valor de Venda");
        jLayeredPane1.add(jLabel5);
        jLabel5.setBounds(60, 120, 80, 16);
        jLayeredPane1.add(jTextField4);
        jTextField4.setBounds(160, 120, 190, 22);

        jLabel6.setText("Quantidade em Estoque");
        jLayeredPane1.add(jLabel6);
        jLabel6.setBounds(20, 150, 130, 16);
        jLayeredPane1.add(jTextField5);
        jTextField5.setBounds(160, 150, 190, 22);

        jButton2.setText("Adicionar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jLayeredPane1.add(jButton2);
        jButton2.setBounds(20, 190, 160, 23);

        jButton3.setText("Salvar Alterações");
        jLayeredPane1.add(jButton3);
        jButton3.setBounds(220, 190, 160, 23);

        add(jLayeredPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
    Produto c;
        
        codigo = Integer.valueOf(jTextField2.getText());
        valorvenda = Float.valueOf(jTextField4.getText());
        quantEstoque = Integer.valueOf(jTextField5.getText());
        c = new Produto(conexaoMySQL, codigo, jTextField3.getText(), valorvenda, quantEstoque);
        mainFrame.adicionarProduto(c);
        
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        
        jLabel6.setVisible(true);
    
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        codigo = Integer.valueOf(jTextField1.getText());
        
        Produto produto = encontrarProduto(codigo);
        
        strCodigo = String.valueOf(produto.getCodigo());
        strValor = String.valueOf(produto.getValorVenda());
        strQuantidade = String.valueOf(produto.getQuantidadeEstoque());
        
        jTextField2.setText(strCodigo);
        jTextField3.setText(produto.getDescricao());
        jTextField4.setText(strValor);
        jTextField5.setText(strQuantidade);
        
        this.revalidate();
        this.repaint();
    }//GEN-LAST:event_jButton1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
